### PR TITLE
Moved to updated Vulkan and fixed type errors

### PR DESCRIPTION
**Pull request by jarrodnorwell**
Nothing too crazy, won't even build on my desktop due to C1060 but did some work.

### CODE REVIEW

**Comment by Zero3K** [comment]
Does this fix anything?

**Comment by Zero3K** [comment]
Please do not switch to VS2022. I do not want to have to install it.

**Comment by jarrodnorwell** [comment]
Should work fine with v141 or v142, I'm using v143 myself, I've just changed a few small things

**Comment by Zero3K** [comment]
Does it improve performance or is just for compilation performance?

**Comment by jarrodnorwell** [comment]
I’m not able to build it strangely, even with 32 GB memory it still runs out.

It’s unlikely to improve performance, the changes I’ve made are to work with Vulkan 1.3.250.0 (latest) and for it to compile successfully on VS2022 with C++20 and C17.

Edit: once I’m able to compile it I’ll try to improve performance and it in general

**Comment by Zero3K** [comment]
Weird. Are you able to compile it with VS 2019 with no modifications?

**Comment by Zero3K** [comment]
It seems to be an issue with how it is handling the json jsnMenuBar code of hps1x64.cpp and hps2x64.cpp.

**Comment by Zero3K** [comment]
You can try simplifying it or make it use something else other than JSON.

**Comment by jarrodnorwell** [comment]
Apologies for the delay @Zero3K, I did notice any compilation fails at both of those so I’ll take a look and see if I’m able to rewrite it a bit to get it compiling

**Comment by Zero3K** [comment]
Any news?

**Pull request closed without merging**
